`ifndef INC_SHMINS_SEQ_ITEM_CONSTRAINTS_SVH
`define INC_SHMINS_SEQ_ITEM_CONSTRAINTS_SVH

// ==================================================================
// AUTO-GENERATED by scripts/gen_shmins_constraints.py -- DO NOT EDIT BY HAND
// ==================================================================

// -- elem_cnt_max upper bound -------------------------------------
constraint c_elem_cnt_max {
  // LDSTE_V: min(data_elem_max, offs_elem_max)
  (creq_itype == LDSTE_V && creq_dtype == DTYP_32) -> elem_cnt_max == (VEC_W / 32);
  (creq_itype == LDSTE_V && creq_atype_w == ATYP_32) -> elem_cnt_max == (VEC_W / 32);
  (creq_itype == LDSTE_V && creq_dtype == DTYP_16 && creq_atype_w == ATYP_16) -> elem_cnt_max == (VEC_W / 16);
  (creq_itype == LDSTE_V && creq_dtype == DTYP_8 && creq_atype_w == ATYP_16) -> elem_cnt_max == (VEC_W / 16);

  // Other itypes: data_elem_max only
  (creq_itype != LDSTE_V && creq_dtype == DTYP_32) -> elem_cnt_max == (VEC_W / 32);
  (creq_itype != LDSTE_V && creq_dtype == DTYP_16) -> elem_cnt_max == (VEC_W / 16);
  (creq_itype != LDSTE_V && creq_dtype == DTYP_8) -> elem_cnt_max == (VEC_W / 8);
}

// -- per-thread creq_len bounded by elem_cnt_max -----------------
constraint c_len {
  foreach(elem_num[t]) {
    elem_num[t] <= elem_cnt_max;
  }
  foreach(creq_len[t]) {
    (creq_dtype == DTYP_32) -> (creq_len[t] == elem_num[t] * 4 && creq_len[t][1:0] == 2'b00);
    (creq_dtype == DTYP_16) -> (creq_len[t] == elem_num[t] * 2 && creq_len[t][0] == 1'b0);
    (creq_dtype == DTYP_8) -> creq_len[t] == elem_num[t];
  }
}

// -- offset alignment --------------------------------------------
constraint c_offs_align {
  foreach(offs_elem[t,k]) {
    (creq_dtype == DTYP_32) -> (offs_elem[t][k][1:0] == 0);
    (creq_dtype == DTYP_16) -> (offs_elem[t][k][0] == 0);
  }
}

// -- offs_elem width / sign-extension consistency ---------------
constraint c_offs_width {
  foreach (offs_elem[t,k]) {
    (creq_atype_w == ATYP_32 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_1B) -> (offs_elem[t][k] >= 0);
    (creq_atype_w == ATYP_32 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_32) -> (offs_elem[t][k] >= 0);
    (creq_atype_w == ATYP_32 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_16) -> (offs_elem[t][k] >= 0);
    (creq_atype_w == ATYP_32 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_8) -> (offs_elem[t][k] >= 0);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_1B) -> (offs_elem[t][k] >= 0 && offs_elem[t][k] <= 65535);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_S && creq_atype_g == GAUTO_1B) -> (offs_elem[t][k] >= -32768 && offs_elem[t][k] <= 32767);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_32) -> (offs_elem[t][k] >= 0 && offs_elem[t][k] <= 262140);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_S && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_32) -> (offs_elem[t][k] >= -131072 && offs_elem[t][k] <= 131068);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_S && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_16) -> (offs_elem[t][k] >= -65536 && offs_elem[t][k] <= 65534);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_16) -> (offs_elem[t][k] >= 0 && offs_elem[t][k] <= 131070);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_U && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_8) -> (offs_elem[t][k] >= 0 && offs_elem[t][k] <= 65535);
    (creq_atype_w == ATYP_16 && creq_atype_s == ATYP_S && creq_atype_g == GAUTO_DW && creq_dtype == DTYP_8) -> (offs_elem[t][k] >= -32768 && offs_elem[t][k] <= 32767);
  }
}

// -- physical address < addr_max ----------------------------------
constraint c_addr_bound {
  foreach (offs_elem[t,k]) {
    // LDST_S / LDST_V: addr = base + offs[0] + k*dbw
    // guard k==0 so constraint is emitted once per thread
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_32 && creq_space == SPACE_LOC && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << VADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) * 4 inside {[0:(1 << VADDR_W)-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_32 && creq_space == SPACE_WRP && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << BADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) * 4 inside {[0:(1 << BADDR_W)-1]})
    );
    // TODO: curr SPACE_BLK mode constraint to unify address is too strong.
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_32 && creq_space == SPACE_BLK) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + creq_len[t] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_16 && creq_space == SPACE_LOC && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << VADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) * 2 inside {[0:(1 << VADDR_W)-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_16 && creq_space == SPACE_WRP && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << BADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) * 2 inside {[0:(1 << BADDR_W)-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_16 && creq_space == SPACE_BLK && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + creq_len[t] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_8 && creq_space == SPACE_LOC && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << VADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) inside {[0:(1 << VADDR_W)-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_8 && creq_space == SPACE_WRP && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << BADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) inside {[0:(1 << BADDR_W)-1]})
    );
    (k == 0 && creq_itype inside {LDST_S, LDST_V} && creq_dtype == DTYP_8 && creq_space == SPACE_BLK && elem_cnt_max > 0) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][0] + (int'(elem_cnt_max) - 1) inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]})
    );

    // LDSTE_S: addr = base + k * offs[0]
    (k == 0 && creq_itype == LDSTE_S && creq_space == SPACE_LOC && elem_cnt_max > 0) -> (
      (offs_elem[t][0] != 0) && // zero cause all address of elem are same
      (offs_elem[t][0] inside {[- (1 << VADDR_W):(1 << VADDR_W)-1]}) && // contraint abs not too big
      ((int'(creq_base[MADDR_W-1:0])) inside {[0:(1 << VADDR_W)-1]}) &&
      ((int'(creq_base[MADDR_W-1:0])) + (int'(elem_cnt_max) - 1) * offs_elem[t][0] inside {[0:(1 << VADDR_W)-1]})
    );

    // LDSTE_V: addr = base + offs[k] (per-element)
    (creq_itype == LDSTE_V && k < int'(elem_cnt_max) && creq_space == SPACE_LOC) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][k] inside {[0:(1 << VADDR_W)-1]})
    );
    (creq_itype == LDSTE_V && k < int'(elem_cnt_max) && creq_space == SPACE_WRP) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][k] inside {[0:(1 << BADDR_W)-1]})
    );
    (creq_itype == LDSTE_V && k < int'(elem_cnt_max) && creq_space == SPACE_BLK) -> (
      ((int'(creq_base[MADDR_W-1:0])) + offs_elem[t][k] inside {[0:(1 << (VADDR_W + 4 + wpid_width))-1]})
    );
  }
}

// -- solver-order experiment --------------------------------------
constraint c_offs_elem_solve_order {
  solve elem_cnt_max, creq_len, creq_itype, creq_space,
        creq_atype_s, creq_atype_g, creq_atype_w, creq_dtype
      before offs_elem;
}

// -- LDSTE_V per-thread uniqueness in SPACE_LOC -------------------
`ifndef SHMINS_DISABLE_SOLVER_COLLISION_CONSTRAINTS
constraint c_ldste_v_loc_unique {
  if (creq_itype == LDSTE_V && creq_space == SPACE_LOC) {
    foreach(offs_elem[t]) {
      unique { offs_elem[t] };
    }
  }
}

// -- LDSTE_V global uniqueness in SPACE_WRP/SPACE_BLK -------------
constraint c_ldste_v_global_unique {
  if (creq_itype == LDSTE_V && (creq_space == SPACE_WRP || creq_space == SPACE_BLK)) {
    unique { offs_elem };
  }
}

// -- LDST thread-range non-overlap in SPACE_WRP/SPACE_BLK ---------
constraint c_ldst_thread_range_no_overlap {
  if ((creq_itype == LDST_V || creq_itype == LDST_S) &&
      (creq_space == SPACE_WRP || creq_space == SPACE_BLK)) {
    foreach (offs_elem[ti]) {
      foreach (offs_elem[tj]) {
        if (ti < tj) {
          (offs_elem[ti][0] + creq_len[ti] <= offs_elem[tj][0]) ||
          (offs_elem[tj][0] + creq_len[tj] <= offs_elem[ti][0]);
        }
      }
    }
  }
}
`endif // SHMINS_DISABLE_SOLVER_COLLISION_CONSTRAINTS

`endif // INC_SHMINS_SEQ_ITEM_CONSTRAINTS_SVH
