`ifndef INC_SHMINS_ENUM_FIELD_SVH
`define INC_SHMINS_ENUM_FIELD_SVH

//===================================================================
// Auto-generated enum string conversion functions
// Generated by gen_enum_str.py
//===================================================================

//---------------------------------------------------------------
// creq_rw_e
//---------------------------------------------------------------

    function automatic string creq_rw_e_to_str(creq_rw_e e);
        case (e)
            SHM_V2M: return "SHM_V2M";
            SHM_M2V: return "SHM_M2V";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_rw_e str_to_creq_rw_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "SHM_V2M") return SHM_V2M;
        else return SHM_M2V;
    endfunction

    function automatic bit value_creq_rw_e_plusargs(string name, ref creq_rw_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_rw_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_dtype_e
//---------------------------------------------------------------

    function automatic string creq_dtype_e_to_str(creq_dtype_e e);
        case (e)
            DTYP_32: return "DTYP_32";
            DTYP_16: return "DTYP_16";
            DTYP_8: return "DTYP_8";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_dtype_e str_to_creq_dtype_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "DTYP_32") return DTYP_32;
        else if (s_upper == "DTYP_16") return DTYP_16;
        else return DTYP_8;
    endfunction

    function automatic bit value_creq_dtype_e_plusargs(string name, ref creq_dtype_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_dtype_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_atype_w_e
//---------------------------------------------------------------

    function automatic string creq_atype_w_e_to_str(creq_atype_w_e e);
        case (e)
            ATYP_32: return "ATYP_32";
            ATYP_16: return "ATYP_16";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_atype_w_e str_to_creq_atype_w_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "ATYP_32") return ATYP_32;
        else return ATYP_16;
    endfunction

    function automatic bit value_creq_atype_w_e_plusargs(string name, ref creq_atype_w_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_atype_w_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_atype_s_e
//---------------------------------------------------------------

    function automatic string creq_atype_s_e_to_str(creq_atype_s_e e);
        case (e)
            ATYP_U: return "ATYP_U";
            ATYP_S: return "ATYP_S";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_atype_s_e str_to_creq_atype_s_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "ATYP_U") return ATYP_U;
        else return ATYP_S;
    endfunction

    function automatic bit value_creq_atype_s_e_plusargs(string name, ref creq_atype_s_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_atype_s_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_atype_g_e
//---------------------------------------------------------------

    function automatic string creq_atype_g_e_to_str(creq_atype_g_e e);
        case (e)
            GAUTO_1B: return "GAUTO_1B";
            GAUTO_DW: return "GAUTO_DW";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_atype_g_e str_to_creq_atype_g_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "GAUTO_1B") return GAUTO_1B;
        else return GAUTO_DW;
    endfunction

    function automatic bit value_creq_atype_g_e_plusargs(string name, ref creq_atype_g_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_atype_g_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_itype_e
//---------------------------------------------------------------

    function automatic string creq_itype_e_to_str(creq_itype_e e);
        case (e)
            LDST_S: return "LDST_S";
            LDST_V: return "LDST_V";
            LDSTE_S: return "LDSTE_S";
            LDSTE_V: return "LDSTE_V";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_itype_e str_to_creq_itype_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "LDST_S") return LDST_S;
        else if (s_upper == "LDST_V") return LDST_V;
        else if (s_upper == "LDSTE_S") return LDSTE_S;
        else return LDSTE_V;
    endfunction

    function automatic bit value_creq_itype_e_plusargs(string name, ref creq_itype_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_itype_e(s);
            return 1;
        end
        return 0;
    endfunction

//---------------------------------------------------------------
// creq_space_e
//---------------------------------------------------------------

    function automatic string creq_space_e_to_str(creq_space_e e);
        case (e)
            SPACE_LOC: return "SPACE_LOC";
            SPACE_WRP: return "SPACE_WRP";
            SPACE_BLK: return "SPACE_BLK";
            default: return "UNKNOWN";
        endcase
    endfunction

    function automatic creq_space_e str_to_creq_space_e(string s);
        string s_upper;
        s_upper = str_toupper(s);
        if (s_upper == "SPACE_LOC") return SPACE_LOC;
        else if (s_upper == "SPACE_WRP") return SPACE_WRP;
        else return SPACE_BLK;
    endfunction

    function automatic bit value_creq_space_e_plusargs(string name, ref creq_space_e var_ref);
        string s;
        if ($value$plusargs({name, "=%s"}, s)) begin
            var_ref = str_to_creq_space_e(s);
            return 1;
        end
        return 0;
    endfunction

`endif // INC_SHMINS_ENUM_FIELD_SVH