`ifndef INC_SHMINS_MST_UNIT_SEQUENCE_SVH
`define INC_SHMINS_MST_UNIT_SEQUENCE_SVH

//------------------------------------------------------------------------------
// @brief Generates configurable normal and VTRANS SHM master transactions.
//
// The sequence owns independent allowed-value domains for normal and VTRANS
// requests, selects a topology for every normal transaction, and creates the
// matching sequence-item subclass. It does not drive the interface or define
// address legality beyond the selected item's constraints and validators.
//------------------------------------------------------------------------------
class shmins_mst_unit_sequence extends uvm_sequence #(shmins_sequence_item);

  // Number of transactions generated by body().
  int m_seq_trans_num = 8;

  // Inclusive per-transaction driver-delay range in cycles.
  int m_seq_delay_max = 16;
  int m_seq_delay_min = 0;

  // Global probability that one transaction is generated as VTRANS.
  int m_vtrans_percentage = 0;

  // Allowed values applied only to normal requests.
  creq_rw_e      m_normal_rw_domain[$];
  creq_dtype_e   m_normal_dtype_domain[$];
  creq_atype_w_e m_normal_atype_w_domain[$];
  creq_atype_s_e m_normal_atype_s_domain[$];
  creq_atype_g_e m_normal_atype_g_domain[$];
  creq_itype_e   m_normal_itype_domain[$];
  creq_space_e   m_normal_space_domain[$];

  // Allowed values applied only to VTRANS requests.
  creq_dtype_e   m_vtrans_dtype_domain[$];
  creq_atype_w_e m_vtrans_atype_w_domain[$];
  creq_atype_s_e m_vtrans_atype_s_domain[$];
  creq_atype_g_e m_vtrans_atype_g_domain[$];
  creq_itype_e   m_vtrans_itype_domain[$];

  //----------------------------------------------------------------------------
  // @brief Constructs a master unit sequence with complete legal domains.
  //
  // @param name UVM object instance name.
  // @post Normal domains contain all legal enum values, VTRANS domains contain
  //       all protocol-supported values, and VTRANS probability is zero.
  //----------------------------------------------------------------------------
  extern function new(string name = "shmins_mst_unit_sequence");

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one dtype.
  //
  // @param value Dtype that must already belong to the current normal domain.
  // @post The normal dtype domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_dtype(creq_dtype_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one offset width.
  //
  // @param value Offset width that must belong to the current normal domain.
  // @post The normal ATYPE_W domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_atype_w(creq_atype_w_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one offset signedness.
  //
  // @param value Signedness that must belong to the current normal domain.
  // @post The normal ATYPE_S domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_atype_s(creq_atype_s_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one offset granularity.
  //
  // @param value Granularity that must belong to the current normal domain.
  // @post The normal ATYPE_G domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_atype_g(creq_atype_g_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one transfer direction.
  //
  // @param value Direction that must belong to the current normal domain.
  // @post The normal RW domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_rw(creq_rw_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one address-generation ITYPE.
  //
  // @param value ITYPE that must belong to the current normal domain.
  // @post The normal ITYPE domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_itype(creq_itype_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts normal requests to one address space.
  //
  // @param value Space that must belong to the current normal domain.
  // @post The normal space domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_space(creq_space_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts VTRANS requests to one supported dtype.
  //
  // @param value Dtype that must belong to the current VTRANS domain.
  // @post The VTRANS dtype domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_vtrans_dtype(creq_dtype_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts VTRANS requests to one offset width.
  //
  // @param value Offset width that must belong to the current VTRANS domain.
  // @post The VTRANS ATYPE_W domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_vtrans_atype_w(creq_atype_w_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts VTRANS requests to one offset signedness.
  //
  // @param value Signedness that must belong to the current VTRANS domain.
  // @post The VTRANS ATYPE_S domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_vtrans_atype_s(creq_atype_s_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts VTRANS requests to one offset granularity.
  //
  // @param value Granularity that must belong to the current VTRANS domain.
  // @post The VTRANS ATYPE_G domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_vtrans_atype_g(creq_atype_g_e value);

  //----------------------------------------------------------------------------
  // @brief Restricts VTRANS requests to one contiguous ITYPE.
  //
  // @param value ITYPE that must belong to the current VTRANS domain.
  // @post The VTRANS ITYPE domain contains only value.
  //----------------------------------------------------------------------------
  extern function void set_fix_vtrans_itype(creq_itype_e value);

  //----------------------------------------------------------------------------
  // @brief Configures the global probability of generating a VTRANS request.
  //
  // @param percentage Integer percentage in the inclusive range 0 through 100.
  // @post Each transaction independently selects VTRANS with this probability.
  //----------------------------------------------------------------------------
  extern function void set_vtrans_en(int percentage = 100);

  //----------------------------------------------------------------------------
  // @brief Configures transaction count and driver-delay range.
  //
  // @param trans_num Number of transactions generated by body().
  // @param delay_max Inclusive maximum driver delay in cycles.
  // @param delay_min Inclusive minimum driver delay in cycles.
  //----------------------------------------------------------------------------
  extern function void config_time(int trans_num = 8, int delay_max = 16, int delay_min = 0);

  //----------------------------------------------------------------------------
  // @brief Applies supported command-line plusargs to sequence configuration.
  //
  // Present CREQ fields shrink normal domains; VTRANS_EN configures the global
  // VTRANS percentage. Missing fields leave their current domains unchanged.
  //----------------------------------------------------------------------------
  extern function void plusargs_override_config();

  //----------------------------------------------------------------------------
  // @brief Generates and sends all configured normal or VTRANS requests.
  //----------------------------------------------------------------------------
  extern virtual task body();

  //----------------------------------------------------------------------------
  // @brief Checks domains, probability, transaction count, and delay range.
  //
  // @pre Configuration APIs and plusarg parsing have completed.
  //----------------------------------------------------------------------------
  extern protected function void validate_configuration();

  //----------------------------------------------------------------------------
  // @brief Selects one normal ITYPE uniformly from its allowed-value domain.
  //
  // @return One legal normal ITYPE used to choose the request subclass.
  //----------------------------------------------------------------------------
  extern protected function creq_itype_e select_normal_itype();

  //----------------------------------------------------------------------------
  // @brief Selects whether the next transaction is VTRANS.
  //
  // @return 1 with m_vtrans_percentage probability; otherwise 0.
  //----------------------------------------------------------------------------
  extern protected function bit select_vtrans();

  //----------------------------------------------------------------------------
  // @brief Creates the topology subclass selected by one normal ITYPE.
  //
  // @param name Object instance name passed to the UVM factory.
  // @param itype Exact normal ITYPE selected for this transaction.
  // @return A contiguous, strided, or indexed request through a base handle.
  //----------------------------------------------------------------------------
  extern protected function shmins_sequence_item create_normal_request(string name, creq_itype_e itype);

  //----------------------------------------------------------------------------
  // @brief Randomizes one normal request inside all normal domains.
  //
  // @param item Request object whose dynamic type matches selected_itype.
  // @param selected_itype Exact per-transaction ITYPE used for class selection.
  // @return 1 when randomization succeeds; otherwise 0.
  //----------------------------------------------------------------------------
  extern protected function bit randomize_normal_request(shmins_sequence_item item, creq_itype_e selected_itype);

  //----------------------------------------------------------------------------
  // @brief Randomizes one VTRANS request inside all VTRANS domains.
  //
  // @param item VTRANS request object to randomize.
  // @return 1 when randomization succeeds; otherwise 0.
  //----------------------------------------------------------------------------
  extern protected function bit randomize_vtrans_request(shmins_sequence_item item);

  `uvm_object_utils(shmins_mst_unit_sequence)
endclass : shmins_mst_unit_sequence

function shmins_mst_unit_sequence::new(string name = "shmins_mst_unit_sequence");
  super.new(name);

  m_normal_rw_domain      = '{SHM_V2M, SHM_M2V};
  m_normal_dtype_domain   = '{DTYP_32, DTYP_16, DTYP_8};
  m_normal_atype_w_domain = '{ATYP_32, ATYP_16};
  m_normal_atype_s_domain = '{ATYP_U, ATYP_S};
  m_normal_atype_g_domain = '{GAUTO_1B, GAUTO_DW};
  m_normal_itype_domain   = '{LDST_S, LDST_V, LDSTE_S, LDSTE_V};
  m_normal_space_domain   = '{SPACE_LOC, SPACE_WRP, SPACE_BLK};

  m_vtrans_dtype_domain   = '{DTYP_16, DTYP_8};
  m_vtrans_atype_w_domain = '{ATYP_32, ATYP_16};
  m_vtrans_atype_s_domain = '{ATYP_U, ATYP_S};
  m_vtrans_atype_g_domain = '{GAUTO_1B, GAUTO_DW};
  m_vtrans_itype_domain   = '{LDST_S, LDST_V};
endfunction : new

function void shmins_mst_unit_sequence::set_fix_dtype(creq_dtype_e value);
  if (!(value inside {m_normal_dtype_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_DTYPE", $sformatf("dtype=%0d is outside the current normal domain", value))
  end
  m_normal_dtype_domain = '{value};
endfunction : set_fix_dtype

function void shmins_mst_unit_sequence::set_fix_atype_w(creq_atype_w_e value);
  if (!(value inside {m_normal_atype_w_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_ATYPE_W", $sformatf("atype_w=%0d is outside the current normal domain", value))
  end
  m_normal_atype_w_domain = '{value};
endfunction : set_fix_atype_w

function void shmins_mst_unit_sequence::set_fix_atype_s(creq_atype_s_e value);
  if (!(value inside {m_normal_atype_s_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_ATYPE_S", $sformatf("atype_s=%0d is outside the current normal domain", value))
  end
  m_normal_atype_s_domain = '{value};
endfunction : set_fix_atype_s

function void shmins_mst_unit_sequence::set_fix_atype_g(creq_atype_g_e value);
  if (!(value inside {m_normal_atype_g_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_ATYPE_G", $sformatf("atype_g=%0d is outside the current normal domain", value))
  end
  m_normal_atype_g_domain = '{value};
endfunction : set_fix_atype_g

function void shmins_mst_unit_sequence::set_fix_rw(creq_rw_e value);
  if (!(value inside {m_normal_rw_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_RW", $sformatf("rw=%0d is outside the current normal domain", value))
  end
  m_normal_rw_domain = '{value};
endfunction : set_fix_rw

function void shmins_mst_unit_sequence::set_fix_itype(creq_itype_e value);
  if (!(value inside {m_normal_itype_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_ITYPE", $sformatf("itype=%0d is outside the current normal domain", value))
  end
  m_normal_itype_domain = '{value};
endfunction : set_fix_itype

function void shmins_mst_unit_sequence::set_fix_space(creq_space_e value);
  if (!(value inside {m_normal_space_domain})) begin
    `uvm_fatal("SHMINS_SEQ_NORMAL_SPACE", $sformatf("space=%0d is outside the current normal domain", value))
  end
  m_normal_space_domain = '{value};
endfunction : set_fix_space

function void shmins_mst_unit_sequence::set_fix_vtrans_dtype(creq_dtype_e value);
  if (!(value inside {m_vtrans_dtype_domain})) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_DTYPE", $sformatf("dtype=%0d is outside the current VTRANS domain", value))
  end
  m_vtrans_dtype_domain = '{value};
endfunction : set_fix_vtrans_dtype

function void shmins_mst_unit_sequence::set_fix_vtrans_atype_w(creq_atype_w_e value);
  if (!(value inside {m_vtrans_atype_w_domain})) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_ATYPE_W", $sformatf("atype_w=%0d is outside the current VTRANS domain", value))
  end
  m_vtrans_atype_w_domain = '{value};
endfunction : set_fix_vtrans_atype_w

function void shmins_mst_unit_sequence::set_fix_vtrans_atype_s(creq_atype_s_e value);
  if (!(value inside {m_vtrans_atype_s_domain})) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_ATYPE_S", $sformatf("atype_s=%0d is outside the current VTRANS domain", value))
  end
  m_vtrans_atype_s_domain = '{value};
endfunction : set_fix_vtrans_atype_s

function void shmins_mst_unit_sequence::set_fix_vtrans_atype_g(creq_atype_g_e value);
  if (!(value inside {m_vtrans_atype_g_domain})) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_ATYPE_G", $sformatf("atype_g=%0d is outside the current VTRANS domain", value))
  end
  m_vtrans_atype_g_domain = '{value};
endfunction : set_fix_vtrans_atype_g

function void shmins_mst_unit_sequence::set_fix_vtrans_itype(creq_itype_e value);
  if (!(value inside {m_vtrans_itype_domain})) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_ITYPE", $sformatf("itype=%0d is outside the current VTRANS domain", value))
  end
  m_vtrans_itype_domain = '{value};
endfunction : set_fix_vtrans_itype

function void shmins_mst_unit_sequence::set_vtrans_en(int percentage = 100);
  if (percentage < 0 || percentage > 100) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_PERCENT", $sformatf("VTRANS percentage=%0d is outside 0 through 100", percentage))
  end
  m_vtrans_percentage = percentage;
endfunction : set_vtrans_en

function void shmins_mst_unit_sequence::config_time(int trans_num = 8, int delay_max = 16, int delay_min = 0);
  m_seq_trans_num = trans_num;
  m_seq_delay_max = delay_max;
  m_seq_delay_min = delay_min;
endfunction : config_time

function void shmins_mst_unit_sequence::plusargs_override_config();
  int vtrans_percentage;
  creq_rw_e rw_value;
  creq_dtype_e dtype_value;
  creq_atype_w_e atype_w_value;
  creq_atype_s_e atype_s_value;
  creq_atype_g_e atype_g_value;
  creq_itype_e itype_value;
  creq_space_e space_value;

  void'($value$plusargs("TRANS_NUM=%d", m_seq_trans_num));
  void'($value$plusargs("TRANS_DELAY_MIN=%d", m_seq_delay_min));
  void'($value$plusargs("TRANS_DELAY_MAX=%d", m_seq_delay_max));
  if ($value$plusargs("VTRANS_EN=%d", vtrans_percentage)) begin
    set_vtrans_en(vtrans_percentage);
  end
  if (value_creq_rw_e_plusargs("CREQ_RW", rw_value)) begin
    set_fix_rw(rw_value);
  end
  if (value_creq_dtype_e_plusargs("CREQ_DTYPE", dtype_value)) begin
    set_fix_dtype(dtype_value);
  end
  if (value_creq_atype_w_e_plusargs("CREQ_ATYPE_W", atype_w_value)) begin
    set_fix_atype_w(atype_w_value);
  end
  if (value_creq_atype_s_e_plusargs("CREQ_ATYPE_S", atype_s_value)) begin
    set_fix_atype_s(atype_s_value);
  end
  if (value_creq_atype_g_e_plusargs("CREQ_ATYPE_G", atype_g_value)) begin
    set_fix_atype_g(atype_g_value);
  end
  if (value_creq_itype_e_plusargs("CREQ_ITYPE", itype_value)) begin
    set_fix_itype(itype_value);
  end
  if (value_creq_space_e_plusargs("CREQ_SPACE", space_value)) begin
    set_fix_space(space_value);
  end
endfunction : plusargs_override_config

function void shmins_mst_unit_sequence::validate_configuration();
  if (m_seq_trans_num < 0) begin
    `uvm_fatal("SHMINS_SEQ_TRANS_NUM", $sformatf("transaction count=%0d must be non-negative", m_seq_trans_num))
  end
  if (m_seq_delay_min < 0 || m_seq_delay_max < m_seq_delay_min) begin
    `uvm_fatal("SHMINS_SEQ_DELAY_RANGE",
               $sformatf("delay range [%0d:%0d] is invalid", m_seq_delay_min, m_seq_delay_max))
  end
  if (m_vtrans_percentage < 0 || m_vtrans_percentage > 100) begin
    `uvm_fatal("SHMINS_SEQ_VTRANS_PERCENT",
               $sformatf("VTRANS percentage=%0d is outside 0 through 100", m_vtrans_percentage))
  end
  if (m_normal_rw_domain.size() == 0 || m_normal_dtype_domain.size() == 0 ||
      m_normal_atype_w_domain.size() == 0 || m_normal_atype_s_domain.size() == 0 ||
      m_normal_atype_g_domain.size() == 0 || m_normal_itype_domain.size() == 0 ||
      m_normal_space_domain.size() == 0) begin
    `uvm_fatal("SHMINS_SEQ_EMPTY_NORMAL_DOMAIN", "all normal allowed-value domains must be non-empty")
  end
  if (m_vtrans_dtype_domain.size() == 0 || m_vtrans_atype_w_domain.size() == 0 ||
      m_vtrans_atype_s_domain.size() == 0 || m_vtrans_atype_g_domain.size() == 0 ||
      m_vtrans_itype_domain.size() == 0) begin
    `uvm_fatal("SHMINS_SEQ_EMPTY_VTRANS_DOMAIN", "all VTRANS allowed-value domains must be non-empty")
  end
endfunction : validate_configuration

function creq_itype_e shmins_mst_unit_sequence::select_normal_itype();
  int unsigned selected_index;

  selected_index = $urandom_range(m_normal_itype_domain.size() - 1, 0);
  return m_normal_itype_domain[selected_index];
endfunction : select_normal_itype

function bit shmins_mst_unit_sequence::select_vtrans();
  if (m_vtrans_percentage == 0) begin
    return 1'b0;
  end
  if (m_vtrans_percentage == 100) begin
    return 1'b1;
  end
  return $urandom_range(99, 0) < m_vtrans_percentage;
endfunction : select_vtrans

function shmins_sequence_item shmins_mst_unit_sequence::create_normal_request(string name, creq_itype_e itype);
  case (itype)
    LDST_S, LDST_V: return shmins_contiguous_sequence_item::type_id::create(name);
    LDSTE_S:        return shmins_strided_sequence_item::type_id::create(name);
    LDSTE_V:        return shmins_indexed_sequence_item::type_id::create(name);
    default: begin
      `uvm_fatal("SHMINS_SEQ_UNSUPPORTED_ITYPE", $sformatf("normal itype=%0d is unsupported", itype))
      return null;
    end
  endcase
endfunction : create_normal_request

function bit shmins_mst_unit_sequence::randomize_normal_request(shmins_sequence_item item,
                                                                 creq_itype_e selected_itype);
  return item.randomize() with {
    creq_rw inside {local::m_normal_rw_domain};
    creq_dtype inside {local::m_normal_dtype_domain};
    creq_atype_w inside {local::m_normal_atype_w_domain};
    creq_atype_s inside {local::m_normal_atype_s_domain};
    creq_atype_g inside {local::m_normal_atype_g_domain};
    creq_itype == local::selected_itype;
    creq_space inside {local::m_normal_space_domain};
    delay_cycle inside {[local::m_seq_delay_min:local::m_seq_delay_max]};
  };
endfunction : randomize_normal_request

function bit shmins_mst_unit_sequence::randomize_vtrans_request(shmins_sequence_item item);
  return item.randomize() with {
    creq_dtype inside {local::m_vtrans_dtype_domain};
    creq_atype_w inside {local::m_vtrans_atype_w_domain};
    creq_atype_s inside {local::m_vtrans_atype_s_domain};
    creq_atype_g inside {local::m_vtrans_atype_g_domain};
    creq_itype inside {local::m_vtrans_itype_domain};
    delay_cycle inside {[local::m_seq_delay_min:local::m_seq_delay_max]};
  };
endfunction : randomize_vtrans_request

task shmins_mst_unit_sequence::body();
  validate_configuration();
  `uvm_info(get_type_name(), "shmins_mst_unit_sequence starting", UVM_HIGH)

  for (int transaction_index = 0; transaction_index < m_seq_trans_num; transaction_index++) begin
    bit vtrans_selected;
    creq_itype_e selected_itype;

    vtrans_selected = select_vtrans();
    if (vtrans_selected) begin
      req = shmins_vtrans_sequence_item::type_id::create($sformatf("vtrans_req_%0d", transaction_index));
    end else begin
      selected_itype = select_normal_itype();
      req = create_normal_request($sformatf("normal_req_%0d", transaction_index), selected_itype);
    end

    start_item(req);
    if (vtrans_selected) begin
      if (!randomize_vtrans_request(req)) begin
        `uvm_fatal("SHMINS_SEQ_VTRANS_RANDOMIZE", $sformatf("VTRANS request %0d randomize failed", transaction_index))
      end
    end else if (!randomize_normal_request(req, selected_itype)) begin
      `uvm_fatal("SHMINS_SEQ_NORMAL_RANDOMIZE", $sformatf("normal request %0d randomize failed", transaction_index))
    end
    req.item_to_rtl();
    finish_item(req);
    get_response(rsp);
  end

  `uvm_info(get_type_name(), "shmins_mst_unit_sequence completed", UVM_HIGH)
endtask : body

`endif // INC_SHMINS_MST_UNIT_SEQUENCE_SVH
