`ifndef INC_SHMINS_SEQUENCE_ITEM_SVH
`define INC_SHMINS_SEQUENCE_ITEM_SVH

typedef enum bit {
  SHM_V2M = 1'b0,
  SHM_M2V = 1'b1
} creq_rw_e;

typedef enum bit [1:0] {
  DTYP_32 = 2'h0,
  DTYP_16 = 2'h1,
  DTYP_8  = 2'h2
} creq_dtype_e;

typedef enum bit [1:0] {
  ATYP_32 = 2'h0,
  ATYP_16 = 2'h1
} creq_atype_w_e;

typedef enum bit {
  ATYP_U = 1'b0,
  ATYP_S = 1'b1
} creq_atype_s_e;

typedef enum bit {
  GAUTO_1B = 1'b0,
  GAUTO_DW = 1'b1
} creq_atype_g_e;

typedef enum bit [1:0] {
  LDST_S  = 2'h0,
  LDST_V  = 2'h1,
  LDSTE_S = 2'h2,
  LDSTE_V = 2'h3
} creq_itype_e;

typedef enum bit [1:0] {
  SPACE_LOC = 2'd0,
  SPACE_WRP = 2'd1,
  SPACE_BLK = 2'd2
} creq_space_e;

//------------------------------------------------------------------------------
// @brief Holds common SHM creq fields and validates generated transactions.
//
// Derived items construct MADDR, base, and offset fields for one address
// topology. This base class owns field encoding, address-space mapping, common
// MADDR checks, byte collision checks, and final validation. It does not select
// a topology and therefore rejects direct randomization.
//------------------------------------------------------------------------------
class shmins_sequence_item extends uvm_sequence_item;
  parameter int unsigned ELEM_MAX_N = VEC_BYTE_N;

  // Normalized result of mapping one legal MADDR to the physical SHM address.
  typedef struct {
    bit                 valid;
    shm_logical_addr_t  logical_addr;
    shm_physical_addr_t physical_addr;
  } shmins_address_result_t;

  // Solver-generated request control fields.
  rand creq_rw_e      creq_rw       = SHM_V2M;
  rand creq_dtype_e   creq_dtype    = DTYP_32;
  rand creq_atype_w_e creq_atype_w  = ATYP_32;
  rand creq_atype_s_e creq_atype_s  = ATYP_U;
  rand creq_atype_g_e creq_atype_g  = GAUTO_1B;
  rand creq_itype_e   creq_itype    = LDST_V;
  rand logic          creq_ack_en   = 1'b0;
  rand logic [3:0]    creq_inv_size = '0;
  rand creq_space_e   creq_space    = SPACE_LOC;

  // Packed request type used at the RTL-facing transaction boundary.
  logic [19:0] creq_typ = '0;

  // Solver-generated request identity, WARP selection, and auxiliary fields.
  rand logic [3:0] creq_info = '0;
  rand logic [ID_W-1:0] creq_id = '0;
  rand logic [$clog2(WARP_N)-1:0] creq_wpid = '0;
  rand logic [$clog2(WARP_N+1)-1:0] creq_wpnum = 1;
  int wpid_width;
  rand logic [BADDR_W-1:0] creq_vaddr = '0;

  // Procedurally generated byte base. Ordinary requests use its low MADDR_W bits.
  logic [47:0] creq_base = '0;

  // Per-thread solver-generated payload. Array indices identify SHM threads.
  rand logic [PRIO_W-1:0] creq_prio[THD_N] = '{THD_N{'0}};
  rand logic [7:0] creq_len[THD_N] = '{THD_N{'0}};
  rand byte unsigned elem_num[THD_N] = '{THD_N{'0}};
  rand logic [VEC_BYTE_N-1:0] creq_vmsk[THD_N] = '{THD_N{'0}};
  rand logic [THD_N-1:0] creq_tmsk = '0;
  rand logic [VEC_BYTE_N-1:0][7:0] creq_vdat[THD_N] = '{THD_N{'0}};

  // Packed offsets generated after the topology-specific decoded offsets.
  logic [VEC_W-1:0] creq_offs_packed[THD_N];

  // Solver-generated driver delay measured in cycles.
  rand int delay_cycle = '0;

  // Optional benchmark policy. M2V duplicate reads remain legal by default.
  bit m2v_unique_enable = 1'b0;

  // Procedurally generated decoded offsets indexed by thread and offset element.
  longint signed offs_elem[THD_N][ELEM_MAX_N];

  // Procedurally generated MADDR indexed by thread and data element.
  // Only entries selected by is_active_element() represent transaction accesses.
  longint signed elem_maddr[THD_N][ELEM_MAX_N];

  // Logical and physical forms of every active generated element address.
  shm_logical_addr_t elem_logical_addr[THD_N][ELEM_MAX_N];
  shm_physical_addr_t elem_physical_addr[THD_N][ELEM_MAX_N];

  // Maximum number of data elements representable by the selected dtype.
  int unsigned elem_cnt_max;

  // Statistics from the latest procedural generation and validation pass.
  int unsigned generation_retry_count;
  int unsigned generation_reject_count;
  int unsigned validation_error_count;

  constraint c_common_control {
    creq_inv_size inside {[0:12]};
    creq_wpid inside {[0:WARP_N-1]};
    creq_wpnum inside {1, 2, 4};
    creq_tmsk != '0;
    creq_vaddr inside {
      [((int'(creq_wpid) % WARP_PER_GID) * WARP_STEP):
       (((int'(creq_wpid) % WARP_PER_GID) + 1) * WARP_STEP - VEC_BYTE_N)]
    };
  }

  constraint c_length {
    foreach (elem_num[thread_idx]) {
      if (creq_dtype == DTYP_32) {
        elem_num[thread_idx] <= VEC_W / 32;
        creq_len[thread_idx] == elem_num[thread_idx] * 4;
      } else if (creq_dtype == DTYP_16) {
        elem_num[thread_idx] <= VEC_W / 16;
        creq_len[thread_idx] == elem_num[thread_idx] * 2;
      } else {
        elem_num[thread_idx] <= VEC_W / 8;
        creq_len[thread_idx] == elem_num[thread_idx];
      }
    }
  }

  //----------------------------------------------------------------------------
  // @brief Constructs a common split-implementation transaction.
  //
  // @param name UVM object instance name.
  //----------------------------------------------------------------------------
  extern function new(string name = "shmins_sequence_item");

  //----------------------------------------------------------------------------
  // @brief Returns one thread's packed offset vector.
  //
  // @param thread_idx Thread index in the range 0 through THD_N-1.
  // @return Packed offset vector for the selected thread.
  //----------------------------------------------------------------------------
  extern function logic [VEC_W-1:0] creq_offs(int thread_idx);

  //----------------------------------------------------------------------------
  // @brief Replaces one thread's packed offset vector.
  //
  // @param thread_idx Thread index in the range 0 through THD_N-1.
  // @param offs_value New packed offset vector.
  //----------------------------------------------------------------------------
  extern function void set_creq_offs(int thread_idx, logic [VEC_W-1:0] offs_value);

  //----------------------------------------------------------------------------
  // @brief Returns the selected data element width in bytes.
  //
  // @return 4, 2, or 1 for DTYP32, DTYP16, or DTYP8; otherwise 0.
  //----------------------------------------------------------------------------
  extern function int unsigned data_byte_w();

  //----------------------------------------------------------------------------
  // @brief Returns the selected data element width in bits.
  //
  // @return Selected data element width in bits, or 0 for an invalid dtype.
  //----------------------------------------------------------------------------
  extern function int unsigned data_bit_w();

  //----------------------------------------------------------------------------
  // @brief Returns the number of selected dtype elements in one data vector.
  //
  // @return Maximum number of data elements, or 0 for an invalid dtype.
  //----------------------------------------------------------------------------
  extern function int unsigned data_elem_max();

  //----------------------------------------------------------------------------
  // @brief Returns the selected raw offset element width in bits.
  //
  // @return 32 or 16 for ATYP32 or ATYP16; otherwise 0.
  //----------------------------------------------------------------------------
  extern function int unsigned offs_bit_w();

  //----------------------------------------------------------------------------
  // @brief Returns the number of raw offset elements in one packed vector.
  //
  // @return Maximum number of offset elements, or 0 for an invalid atype.
  //----------------------------------------------------------------------------
  extern function int unsigned offs_elem_max();

  //----------------------------------------------------------------------------
  // @brief Returns the decoded offset scaling shift.
  //
  // @return Zero for GAUTO_1B, or log2(dtype byte width) for GAUTO_DW.
  //----------------------------------------------------------------------------
  extern function int unsigned gran_shift();

  //----------------------------------------------------------------------------
  // @brief Returns the legacy dtype alignment mask.
  //
  // @return 3, 1, or 0 for DTYP32, DTYP16, or DTYP8.
  //----------------------------------------------------------------------------
  extern function int unsigned align_mask();

  //----------------------------------------------------------------------------
  // @brief Returns an encoded address upper bound for the selected space.
  //
  // @return One past the LOC, legacy WRP, or current group-relative BLK encoded range.
  //----------------------------------------------------------------------------
  extern function int unsigned addr_max();

  //----------------------------------------------------------------------------
  // @brief Returns the maximum data element count supported by dtype and ITYPE.
  //
  // @return Data-vector capacity, additionally limited by offset capacity for LDSTE_V.
  //----------------------------------------------------------------------------
  extern function int unsigned max_elem_cnt();

  //----------------------------------------------------------------------------
  // @brief Returns one thread's number of data elements from creq_len.
  //
  // @param thread_idx Thread index to inspect.
  // @return Element count, or 0 for an invalid thread or dtype.
  //----------------------------------------------------------------------------
  extern function int unsigned thread_elem_cnt(int thread_idx);

  //----------------------------------------------------------------------------
  // @brief Computes one legacy MADDR from decoded procedural offset fields.
  //
  // @param thread_idx Source thread index.
  // @param elem_idx Data element index.
  // @return Address computed from creq_base, ITYPE, dtype, and offs_elem.
  //----------------------------------------------------------------------------
  extern function int phys_addr(int thread_idx, int elem_idx);

  //----------------------------------------------------------------------------
  // @brief Determines whether one thread and element produce an access.
  //
  // @param thread_idx Thread index to inspect.
  // @param elem_idx Data element index to inspect.
  // @return 1 when thread mask, length, and element mask select the element.
  //----------------------------------------------------------------------------
  extern function bit is_active_element(int thread_idx, int elem_idx);

  //----------------------------------------------------------------------------
  // @brief Computes the decoded offset range selected by ATYPE_W/S/G and dtype.
  //
  // @param decode_lower Inclusive minimum decoded byte offset.
  // @param decode_upper Inclusive maximum decoded byte offset.
  //----------------------------------------------------------------------------
  extern function void decoded_offset_range(output longint signed decode_lower,
                                            output longint signed decode_upper);

  //----------------------------------------------------------------------------
  // @brief Checks whether a decoded byte offset can be packed without loss.
  //
  // @param offset Decoded byte offset to check.
  // @return 1 when offset has the selected granularity and raw encoding range.
  //----------------------------------------------------------------------------
  extern function bit check_offset_encodable(longint signed offset);

  //----------------------------------------------------------------------------
  // @brief Encodes one decoded byte offset into a 32-bit raw container.
  //
  // @param offset Decoded byte offset to encode.
  // @param raw_bits Encoded raw bits; upper bits are zero for ATYP16.
  // @return 1 when encoding succeeds; otherwise 0 and raw_bits is zero.
  //----------------------------------------------------------------------------
  extern function bit encode_offset(longint signed offset, output logic [31:0] raw_bits);

  //----------------------------------------------------------------------------
  // @brief Decodes one offset element from the packed transaction field.
  //
  // @param thread_idx Thread containing the packed offset.
  // @param elem_idx Raw offset element index within the packed vector.
  // @return Sign- or zero-extended and granularity-scaled byte offset.
  //----------------------------------------------------------------------------
  extern function longint signed decode_packed_offset(int thread_idx, int elem_idx);

  //----------------------------------------------------------------------------
  // @brief Returns the encoded bytes allocated to each BANK/WARP address field.
  //
  // @return 12 KiB when interleave is at most 4 KiB; otherwise 16 KiB.
  //----------------------------------------------------------------------------
  extern function longint unsigned coded_warp_bytes();

  //----------------------------------------------------------------------------
  // @brief Computes a fast left-closed, right-open MADDR encoding range.
  //
  // The range excludes impossible space configuration values but can include
  // 8/16 KiB interleave holes. BLK always starts at zero and spans only the
  // creq_wpid-selected WARP group. Call legal_space_maddr_check() after sampling.
  //
  // @param space_lower Inclusive MADDR lower bound.
  // @param space_upper Exclusive MADDR upper bound.
  // @return 1 for a supported and configured address space; otherwise 0.
  //----------------------------------------------------------------------------
  extern function bit fast_legal_space_range(output longint signed space_lower,
                                             output longint signed space_upper);

  //----------------------------------------------------------------------------
  // @brief Maps one MADDR to its physical BANK and BADDR.
  //
  // @param thread_idx Source thread, used as BANK in SPACE_LOC.
  // @param maddr Unified byte address to map.
  // @return Mapping result with valid cleared for range, hole, alignment, or WARP-control failures.
  //----------------------------------------------------------------------------
  extern function shmins_address_result_t map_maddr(int thread_idx, longint signed maddr);

  //----------------------------------------------------------------------------
  // @brief Checks one element MADDR against alignment and address-space rules.
  //
  // @param thread_idx Source thread for LOC BANK selection and diagnostics.
  // @param maddr Unified byte address to check.
  // @return 1 when the MADDR is in the fast range and maps to a legal address.
  //----------------------------------------------------------------------------
  extern function bit legal_space_maddr_check(int thread_idx, longint signed maddr);

  //----------------------------------------------------------------------------
  // @brief Forms a globally comparable key for one physical SHM byte.
  //
  // @param physical_addr Physical BANK, gid, and BADDR.
  // @return Composite key containing BANK, gid, and BADDR.
  //----------------------------------------------------------------------------
  extern function longint unsigned make_physical_byte_key(shm_physical_addr_t physical_addr);

  //----------------------------------------------------------------------------
  // @brief Backfills logical and physical address arrays from generated MADDRs.
  //
  // @return 1 when every active element maps successfully; otherwise 0.
  //----------------------------------------------------------------------------
  extern function bit populate_element_addresses();

  //----------------------------------------------------------------------------
  // @brief Selects an M2V writeback BADDR disjoint from every read byte.
  //
  // @return 1 for V2M or for a legal M2V writeback address; otherwise 0.
  //----------------------------------------------------------------------------
  extern function bit generate_m2v_writeback_address();

  //----------------------------------------------------------------------------
  // @brief Returns whether this transaction requires physical byte uniqueness.
  //
  // @return 1 for V2M or explicitly enabled M2V uniqueness; otherwise 0.
  //----------------------------------------------------------------------------
  extern function bit uniqueness_required();

  //----------------------------------------------------------------------------
  // @brief Checks active generated elements for physical byte overlap.
  //
  // @return 1 when uniqueness is disabled or all active byte keys are distinct.
  // @pre elem_maddr contains generated values for all active elements.
  //----------------------------------------------------------------------------
  extern function bit check_active_maddr_byte_uniqueness();

  //----------------------------------------------------------------------------
  // @brief Intersects a running base range with one base-plus-offset target.
  //
  // @param target Value satisfying target = base + decoded offset.
  // @param base_lower Inclusive running lower bound, updated in place.
  // @param base_upper Inclusive running upper bound, updated in place.
  // @return 1 when the clipped and stimulus-aligned intersection is non-empty.
  //----------------------------------------------------------------------------
  extern function bit intersect_creq_base_range(longint signed target,
                                                inout longint signed base_lower,
                                                inout longint signed base_upper);

  //----------------------------------------------------------------------------
  // @brief Divides a signed numerator by a positive divisor and rounds down.
  //
  // @param numerator Signed dividend.
  // @param divisor Positive divisor.
  // @return Mathematical floor of numerator divided by divisor.
  //----------------------------------------------------------------------------
  extern function longint signed floor_divide_signed(longint signed numerator, longint signed divisor);

  //----------------------------------------------------------------------------
  // @brief Divides a signed numerator by a positive divisor and rounds up.
  //
  // @param numerator Signed dividend.
  // @param divisor Positive divisor.
  // @return Mathematical ceiling of numerator divided by divisor.
  //----------------------------------------------------------------------------
  extern function longint signed ceil_divide_signed(longint signed numerator, longint signed divisor);

  //----------------------------------------------------------------------------
  // @brief Samples an aligned integer from a left-closed, right-open range.
  //
  // @param range_lower Inclusive signed lower bound.
  // @param range_upper Exclusive signed upper bound.
  // @param alignment Required positive power-of-two alignment.
  // @param sampled_value Selected value when the function succeeds.
  // @return 1 when the range contains at least one aligned value.
  //----------------------------------------------------------------------------
  extern function bit sample_aligned_value(longint signed range_lower,
                                           longint signed range_upper,
                                           int unsigned alignment,
                                           output longint signed sampled_value);

  //----------------------------------------------------------------------------
  // @brief Samples and stores creq_base from an inclusive feasible range.
  //
  // The first implementation deliberately selects a dtype-aligned base for
  // GAUTO_1B as a stimulus restriction. GAUTO_DW requires that alignment.
  //
  // @param base_lower Inclusive feasible base lower bound.
  // @param base_upper Inclusive feasible base upper bound.
  // @return 1 when an aligned base is generated and stored.
  // @post creq_base high bits are zero on success.
  //----------------------------------------------------------------------------
  extern function bit sample_creq_base(longint signed base_lower, longint signed base_upper);

  //----------------------------------------------------------------------------
  // @brief Runs topology-independent checks on the generated MADDR array.
  //
  // @return 1 when every active MADDR is legal and required byte keys are unique.
  //----------------------------------------------------------------------------
  extern function bit check_generated_maddrs();

  //----------------------------------------------------------------------------
  // @brief Orchestrates procedural address generation, packing, and validation.
  //
  // @post creq_base, offsets, elem_maddr, packed offsets, and statistics describe one transaction.
  //----------------------------------------------------------------------------
  extern function void post_randomize();

  //----------------------------------------------------------------------------
  // @brief Encodes all procedural offsets into creq_offs_packed.
  //
  // @post Every packed offset element decodes to its corresponding offs_elem value.
  //----------------------------------------------------------------------------
  extern function void pack_offsets();

  //----------------------------------------------------------------------------
  // @brief Independently validates the final packed transaction.
  //
  // Recomputes each active MADDR from creq_base and packed offsets, compares it
  // with elem_maddr, and checks space legality and physical byte collisions.
  //----------------------------------------------------------------------------
  extern function void validate_transaction();

  //----------------------------------------------------------------------------
  // @brief Unpacks creq_typ into the public request control fields.
  //----------------------------------------------------------------------------
  extern function void rtl_to_item();

  //----------------------------------------------------------------------------
  // @brief Packs the public request control fields into creq_typ.
  //----------------------------------------------------------------------------
  extern function void item_to_rtl();

  //----------------------------------------------------------------------------
  // @brief Copies all transaction, generated-model, and statistic fields.
  //
  // @param rhs Source UVM object, which must cast to shmins_sequence_item.
  //----------------------------------------------------------------------------
  extern function void do_copy(uvm_object rhs);

  //----------------------------------------------------------------------------
  // @brief Compares this transaction with another SHM input transaction.
  //
  // @param rhs Transaction to compare through registered UVM fields.
  // @return 1 when registered transaction fields compare equal.
  //----------------------------------------------------------------------------
  extern function bit compare_item(shmins_sequence_item rhs);

  //----------------------------------------------------------------------------
  // @brief Generates topology-specific MADDR, base, and decoded offset fields.
  //
  // Derived generators override this method. The base remains concrete so a
  // future monitor can construct it without randomizing it.
  //----------------------------------------------------------------------------
  extern virtual protected function void generate_address_fields();

  //----------------------------------------------------------------------------
  // @brief Recomputes one MADDR from the final packed transaction fields.
  //
  // @param thread_idx Source thread index.
  // @param elem_idx Data element index.
  // @return Topology-specific MADDR, or a negative value in the base implementation.
  //----------------------------------------------------------------------------
  extern virtual protected function longint signed calculate_maddr(int thread_idx, int elem_idx);

  `uvm_object_utils_begin(shmins_sequence_item)
    `uvm_field_enum(creq_rw_e, creq_rw, UVM_DEFAULT)
    `uvm_field_enum(creq_dtype_e, creq_dtype, UVM_DEFAULT)
    `uvm_field_enum(creq_atype_w_e, creq_atype_w, UVM_DEFAULT)
    `uvm_field_enum(creq_atype_s_e, creq_atype_s, UVM_DEFAULT)
    `uvm_field_enum(creq_atype_g_e, creq_atype_g, UVM_DEFAULT)
    `uvm_field_enum(creq_itype_e, creq_itype, UVM_DEFAULT)
    `uvm_field_enum(creq_space_e, creq_space, UVM_DEFAULT)
    `uvm_field_int(creq_info, UVM_DEFAULT)
    `uvm_field_int(creq_ack_en, UVM_DEFAULT)
    `uvm_field_int(creq_inv_size, UVM_DEFAULT)
    `uvm_field_int(creq_typ, UVM_DEFAULT)
    `uvm_field_int(creq_id, UVM_DEFAULT)
    `uvm_field_int(creq_wpid, UVM_DEFAULT)
    `uvm_field_int(creq_wpnum, UVM_DEFAULT)
    `uvm_field_int(creq_vaddr, UVM_DEFAULT)
    `uvm_field_int(creq_base, UVM_DEFAULT)
    `uvm_field_int(creq_tmsk, UVM_DEFAULT)
    `uvm_field_int(delay_cycle, UVM_DEFAULT)
    `uvm_field_int(m2v_unique_enable, UVM_DEFAULT)
    `uvm_field_sarray_int(creq_prio, UVM_DEFAULT)
    `uvm_field_sarray_int(creq_len, UVM_DEFAULT)
    `uvm_field_sarray_int(elem_num, UVM_DEFAULT)
    `uvm_field_sarray_int(creq_vmsk, UVM_DEFAULT)
    `uvm_field_sarray_int(creq_offs_packed, UVM_DEFAULT)
    `uvm_field_sarray_int(creq_vdat, UVM_DEFAULT)
  `uvm_object_utils_end
endclass : shmins_sequence_item

function shmins_sequence_item::new(string name = "shmins_sequence_item");
  super.new(name);
endfunction : new

function logic [VEC_W-1:0] shmins_sequence_item::creq_offs(int thread_idx);
  return creq_offs_packed[thread_idx];
endfunction : creq_offs

function void shmins_sequence_item::set_creq_offs(int thread_idx, logic [VEC_W-1:0] offs_value);
  creq_offs_packed[thread_idx] = offs_value;
endfunction : set_creq_offs

function int unsigned shmins_sequence_item::data_byte_w();
  case (creq_dtype)
    DTYP_32: return 4;
    DTYP_16: return 2;
    DTYP_8:  return 1;
    default: return 0;
  endcase
endfunction : data_byte_w

function int unsigned shmins_sequence_item::data_bit_w();
  return data_byte_w() * 8;
endfunction : data_bit_w

function int unsigned shmins_sequence_item::data_elem_max();
  return data_bit_w() == 0 ? 0 : VEC_W / data_bit_w();
endfunction : data_elem_max

function int unsigned shmins_sequence_item::offs_bit_w();
  case (creq_atype_w)
    ATYP_32: return 32;
    ATYP_16: return 16;
    default: return 0;
  endcase
endfunction : offs_bit_w

function int unsigned shmins_sequence_item::offs_elem_max();
  return offs_bit_w() == 0 ? 0 : VEC_W / offs_bit_w();
endfunction : offs_elem_max

function int unsigned shmins_sequence_item::gran_shift();
  if (creq_atype_g == GAUTO_1B) begin
    return 0;
  end
  case (creq_dtype)
    DTYP_32: return 2;
    DTYP_16: return 1;
    DTYP_8:  return 0;
    default: return 0;
  endcase
endfunction : gran_shift

function int unsigned shmins_sequence_item::align_mask();
  case (creq_dtype)
    DTYP_32: return 32'h3;
    DTYP_16: return 32'h1;
    DTYP_8:  return 32'h0;
    default: return 32'h0;
  endcase
endfunction : align_mask

function int unsigned shmins_sequence_item::addr_max();
  case (creq_space)
    SPACE_LOC: return WARP_STEP;
    SPACE_WRP: return 1 << BADDR_W;
    SPACE_BLK: return int'(coded_warp_bytes() * BANK_N * int'(creq_wpnum));
    default:   return WARP_STEP;
  endcase
endfunction : addr_max

function int unsigned shmins_sequence_item::max_elem_cnt();
  if (creq_itype == LDSTE_V) begin
    return data_elem_max() < offs_elem_max() ? data_elem_max() : offs_elem_max();
  end
  return data_elem_max();
endfunction : max_elem_cnt

function int unsigned shmins_sequence_item::thread_elem_cnt(int thread_idx);
  if (thread_idx < 0 || thread_idx >= THD_N || data_byte_w() == 0) begin
    return 0;
  end
  return int'(creq_len[thread_idx]) / data_byte_w();
endfunction : thread_elem_cnt

function int shmins_sequence_item::phys_addr(int thread_idx, int elem_idx);
  longint signed base_maddr;

  base_maddr = longint'(creq_base[MADDR_W-1:0]);
  case (creq_itype)
    LDST_S, LDST_V: return int'(base_maddr + offs_elem[thread_idx][0] + elem_idx * data_byte_w());
    LDSTE_S:        return int'(base_maddr + elem_idx * offs_elem[thread_idx][0]);
    LDSTE_V:        return int'(base_maddr + offs_elem[thread_idx][elem_idx]);
    default:        return 0;
  endcase
endfunction : phys_addr

function bit shmins_sequence_item::is_active_element(int thread_idx, int elem_idx);
  if (thread_idx < 0 || thread_idx >= THD_N || elem_idx < 0 || elem_idx >= ELEM_MAX_N) begin
    return 1'b0;
  end
  return creq_tmsk[thread_idx] === 1'b1 && elem_idx < thread_elem_cnt(thread_idx) &&
         creq_vmsk[thread_idx][elem_idx] === 1'b1;
endfunction : is_active_element

function void shmins_sequence_item::decoded_offset_range(output longint signed decode_lower,
                                                         output longint signed decode_upper);
  longint signed raw_lower;
  longint signed raw_upper;
  longint signed scale;
  int unsigned width;

  width = offs_bit_w();
  if (width == 0) begin
    decode_lower = 0;
    decode_upper = -1;
    return;
  end

  if (creq_atype_s == ATYP_S) begin
    raw_lower = -(longint'(1) << (width - 1));
    raw_upper = (longint'(1) << (width - 1)) - 1;
  end else begin
    raw_lower = 0;
    raw_upper = (longint'(1) << width) - 1;
  end
  scale = longint'(1) << gran_shift();
  decode_lower = raw_lower * scale;
  decode_upper = raw_upper * scale;
endfunction : decoded_offset_range

function bit shmins_sequence_item::check_offset_encodable(longint signed offset);
  longint signed decode_lower;
  longint signed decode_upper;
  longint signed scale;

  decoded_offset_range(decode_lower, decode_upper);
  scale = longint'(1) << gran_shift();
  if (data_byte_w() == 0 || offs_bit_w() == 0 || offset % scale != 0) begin
    return 1'b0;
  end
  return offset >= decode_lower && offset <= decode_upper;
endfunction : check_offset_encodable

function bit shmins_sequence_item::encode_offset(longint signed offset, output logic [31:0] raw_bits);
  longint signed raw_value;

  raw_bits = '0;
  if (!check_offset_encodable(offset)) begin
    return 1'b0;
  end
  raw_value = offset / (longint'(1) << gran_shift());
  raw_bits = raw_value[31:0];
  if (offs_bit_w() == 16) begin
    raw_bits[31:16] = '0;
  end
  return 1'b1;
endfunction : encode_offset

function longint signed shmins_sequence_item::decode_packed_offset(int thread_idx, int elem_idx);
  logic [31:0] raw_bits;
  longint signed raw_value;
  int unsigned width;

  width = offs_bit_w();
  raw_bits = '0;
  if (thread_idx < 0 || thread_idx >= THD_N || elem_idx < 0 || elem_idx >= offs_elem_max()) begin
    return 0;
  end

  case (width)
    32: raw_bits = creq_offs_packed[thread_idx][elem_idx*32 +: 32];
    16: raw_bits[15:0] = creq_offs_packed[thread_idx][elem_idx*16 +: 16];
    default: return 0;
  endcase

  if (creq_atype_s == ATYP_S) begin
    case (width)
      32: raw_value = longint'($signed(raw_bits));
      16: raw_value = longint'($signed(raw_bits[15:0]));
      default: raw_value = 0;
    endcase
  end else begin
    raw_value = longint'($unsigned(raw_bits));
  end
  return raw_value * (longint'(1) << gran_shift());
endfunction : decode_packed_offset

function longint unsigned shmins_sequence_item::coded_warp_bytes();
  longint unsigned interleave_bytes;

  interleave_bytes = longint'(1) << (int'(creq_inv_size) + 2);
  return interleave_bytes <= 4096 ? WARP_STEP : 16 * 1024;
endfunction : coded_warp_bytes

function bit shmins_sequence_item::fast_legal_space_range(output longint signed space_lower,
                                                          output longint signed space_upper);
  longint signed coded_bytes;

  space_lower = 0;
  space_upper = 0;
  coded_bytes = longint'(coded_warp_bytes());
  case (creq_space)
    SPACE_LOC: space_upper = WARP_STEP;
    SPACE_WRP: space_upper = coded_bytes * BANK_N;
    SPACE_BLK: begin
      if ($isunknown({creq_wpnum, creq_wpid}) || !(creq_wpnum inside {1, 2, 4}) ||
          int'(creq_wpid) >= WARP_N) begin
        return 1'b0;
      end
      space_upper = coded_bytes * BANK_N * int'(creq_wpnum);
    end
    default: return 1'b0;
  endcase
  return space_upper > space_lower;
endfunction : fast_legal_space_range

function shmins_sequence_item::shmins_address_result_t shmins_sequence_item::map_maddr(int thread_idx,
                                                                                      longint signed maddr);
  shmins_address_result_t result;
  longint unsigned address;
  longint unsigned coded_bytes;
  longint unsigned interleave_bytes;
  longint unsigned interleave_offset;
  longint unsigned interleave_index;

  result = '{default:'0};
  if (maddr < 0 || data_byte_w() == 0 || maddr % longint'(data_byte_w()) != 0) begin
    return result;
  end

  address = longint'(maddr);
  coded_bytes = coded_warp_bytes();
  interleave_bytes = longint'(1) << (int'(creq_inv_size) + 2);
  interleave_offset = address % interleave_bytes;

  case (creq_space)
    SPACE_LOC: begin
      if (thread_idx < 0 || thread_idx >= BANK_N || address >= WARP_STEP) begin
        return result;
      end
      result.logical_addr.bank_id = shm_bank_id_t'(thread_idx);
      result.logical_addr.laddr = shm_warp_laddr_t'(address);
      result.logical_addr.warp_id = shm_warp_id_t'(creq_wpid);
    end

    SPACE_WRP: begin
      if (address >= coded_bytes * BANK_N) begin
        return result;
      end
      result.logical_addr.bank_id = shm_bank_id_t'((address / interleave_bytes) % BANK_N);
      interleave_index = address / (interleave_bytes * BANK_N);
      result.logical_addr.laddr = shm_warp_laddr_t'(interleave_index * interleave_bytes + interleave_offset);
      result.logical_addr.warp_id = shm_warp_id_t'(creq_wpid);
    end

    SPACE_BLK: begin
      longint unsigned blk_span;
      longint unsigned warp_group;
      longint unsigned warp_offs;
      int unsigned warps_per_group;

      if ($isunknown({creq_wpnum, creq_wpid}) || !(creq_wpnum inside {1, 2, 4}) ||
          int'(creq_wpid) >= WARP_N) begin
        return result;
      end
      warps_per_group = int'(creq_wpnum);
      blk_span = coded_bytes * BANK_N * warps_per_group;
      if (address >= blk_span) begin
        return result;
      end
      warp_group = int'(creq_wpid) / warps_per_group;
      result.logical_addr.bank_id = shm_bank_id_t'((address / interleave_bytes) % BANK_N);
      warp_offs = (address / (interleave_bytes * BANK_N)) % warps_per_group;
      interleave_index = (address / (interleave_bytes * BANK_N * warps_per_group)) %
                         (coded_bytes / interleave_bytes);
      result.logical_addr.laddr = shm_warp_laddr_t'(interleave_index * interleave_bytes + interleave_offset);
      result.logical_addr.warp_id = shm_warp_id_t'(warp_group * warps_per_group + warp_offs);
    end

    default: return result;
  endcase

  if (int'(result.logical_addr.laddr) >= WARP_STEP || int'(result.logical_addr.warp_id) >= WARP_N) begin
    return '{default:'0};
  end
  if (!logical_to_physical_addr(result.logical_addr, result.physical_addr)) begin
    return '{default:'0};
  end
  result.valid = 1'b1;
  return result;
endfunction : map_maddr

function bit shmins_sequence_item::legal_space_maddr_check(int thread_idx, longint signed maddr);
  longint signed space_lower;
  longint signed space_upper;
  shmins_address_result_t mapped;

  if (!fast_legal_space_range(space_lower, space_upper) || maddr < space_lower || maddr >= space_upper) begin
    return 1'b0;
  end
  mapped = map_maddr(thread_idx, maddr);
  return mapped.valid;
endfunction : legal_space_maddr_check

function longint unsigned shmins_sequence_item::make_physical_byte_key(shm_physical_addr_t physical_addr);
  return shm_util_package::physical_byte_key(physical_addr);
endfunction : make_physical_byte_key

function bit shmins_sequence_item::populate_element_addresses();
  foreach (elem_logical_addr[thread_idx, elem_idx]) begin
    elem_logical_addr[thread_idx][elem_idx] = '0;
    elem_physical_addr[thread_idx][elem_idx] = '0;
  end

  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N; elem_idx++) begin
      shmins_address_result_t mapped;

      if (!is_active_element(thread_idx, elem_idx)) begin
        continue;
      end
      mapped = map_maddr(thread_idx, elem_maddr[thread_idx][elem_idx]);
      if (!mapped.valid) begin
        return 1'b0;
      end
      elem_logical_addr[thread_idx][elem_idx] = mapped.logical_addr;
      elem_physical_addr[thread_idx][elem_idx] = mapped.physical_addr;
    end
  end
  return 1'b1;
endfunction : populate_element_addresses

function bit shmins_sequence_item::generate_m2v_writeback_address();
  bit read_bytes[longint unsigned];
  int unsigned warp_base;
  int unsigned candidate_span;
  int unsigned random_start;

  if (creq_rw != SHM_M2V) begin
    return 1'b1;
  end

  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N; elem_idx++) begin
      if (!is_active_element(thread_idx, elem_idx)) begin
        continue;
      end
      for (int byte_lane = 0; byte_lane < data_byte_w(); byte_lane++) begin
        shm_physical_addr_t byte_addr = elem_physical_addr[thread_idx][elem_idx];
        byte_addr.baddr += shm_baddr_t'(byte_lane);
        read_bytes[make_physical_byte_key(byte_addr)] = 1'b1;
      end
    end
  end

  warp_base = (int'(creq_wpid) % WARP_PER_GID) * WARP_STEP;
  candidate_span = WARP_STEP - VEC_BYTE_N + 1;
  random_start = $urandom_range(candidate_span - 1, 0);
  for (int unsigned attempt = 0; attempt < candidate_span; attempt++) begin
    int unsigned candidate = warp_base + ((random_start + attempt) % candidate_span);
    bit overlaps = 1'b0;

    for (int thread_idx = 0; thread_idx < THD_N && !overlaps; thread_idx++) begin
      for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N && !overlaps;
           elem_idx++) begin
        if (!is_active_element(thread_idx, elem_idx)) begin
          continue;
        end
        for (int byte_lane = 0; byte_lane < data_byte_w(); byte_lane++) begin
          shm_physical_addr_t write_addr;

          write_addr.bank_id = shm_bank_id_t'(thread_idx);
          write_addr.gid = shm_gid_t'(int'(creq_wpid) / WARP_PER_GID);
          write_addr.baddr = shm_baddr_t'(candidate + elem_idx * data_byte_w() + byte_lane);
          if (read_bytes.exists(make_physical_byte_key(write_addr))) begin
            overlaps = 1'b1;
            break;
          end
        end
      end
    end
    if (!overlaps) begin
      creq_vaddr = shm_baddr_t'(candidate);
      return 1'b1;
    end
  end
  return 1'b0;
endfunction : generate_m2v_writeback_address

function bit shmins_sequence_item::uniqueness_required();
  return creq_rw == SHM_V2M || m2v_unique_enable;
endfunction : uniqueness_required

function bit shmins_sequence_item::check_active_maddr_byte_uniqueness();
  bit used_bytes[longint unsigned];

  if (!uniqueness_required()) begin
    return 1'b1;
  end

  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N; elem_idx++) begin
      shmins_address_result_t mapped;

      if (!is_active_element(thread_idx, elem_idx)) begin
        continue;
      end
      mapped = map_maddr(thread_idx, elem_maddr[thread_idx][elem_idx]);
      if (!mapped.valid) begin
        return 1'b0;
      end
      for (int byte_lane = 0; byte_lane < data_byte_w(); byte_lane++) begin
        longint unsigned key;

        begin
          shm_physical_addr_t byte_addr = mapped.physical_addr;
          byte_addr.baddr += shm_baddr_t'(byte_lane);
          key = make_physical_byte_key(byte_addr);
        end
        if (used_bytes.exists(key)) begin
          return 1'b0;
        end
        used_bytes[key] = 1'b1;
      end
    end
  end
  return 1'b1;
endfunction : check_active_maddr_byte_uniqueness

function bit shmins_sequence_item::intersect_creq_base_range(longint signed target,
                                                             inout longint signed base_lower,
                                                             inout longint signed base_upper);
  longint signed candidate_lower;
  longint signed candidate_upper;
  longint signed decode_lower;
  longint signed decode_upper;
  longint signed maximum_base;
  longint signed alignment;

  decoded_offset_range(decode_lower, decode_upper);
  if (decode_upper < decode_lower || data_byte_w() == 0) begin
    return 1'b0;
  end

  candidate_lower = target - decode_upper;
  candidate_upper = target - decode_lower;
  maximum_base = (longint'(1) << MADDR_W) - 1;
  if (base_lower < 0) begin
    base_lower = 0;
  end
  if (base_upper > maximum_base) begin
    base_upper = maximum_base;
  end
  if (base_lower < candidate_lower) begin
    base_lower = candidate_lower;
  end
  if (base_upper > candidate_upper) begin
    base_upper = candidate_upper;
  end
  if (base_lower < 0) begin
    base_lower = 0;
  end
  if (base_upper > maximum_base) begin
    base_upper = maximum_base;
  end

  // Temporary stimulus restriction: keep base and decoded offsets dtype-aligned.
  alignment = data_byte_w();
  base_lower = ((base_lower + alignment - 1) / alignment) * alignment;
  base_upper = (base_upper / alignment) * alignment;
  return base_lower <= base_upper;
endfunction : intersect_creq_base_range

function longint signed shmins_sequence_item::floor_divide_signed(longint signed numerator,
                                                                  longint signed divisor);
  longint signed quotient;
  longint signed remainder;

  if (divisor <= 0) begin
    return 0;
  end
  quotient = numerator / divisor;
  remainder = numerator % divisor;
  if (remainder != 0 && numerator < 0) begin
    quotient--;
  end
  return quotient;
endfunction : floor_divide_signed

function longint signed shmins_sequence_item::ceil_divide_signed(longint signed numerator,
                                                                 longint signed divisor);
  longint signed quotient;
  longint signed remainder;

  if (divisor <= 0) begin
    return 0;
  end
  quotient = numerator / divisor;
  remainder = numerator % divisor;
  if (remainder != 0 && numerator > 0) begin
    quotient++;
  end
  return quotient;
endfunction : ceil_divide_signed

function bit shmins_sequence_item::sample_aligned_value(longint signed range_lower,
                                                        longint signed range_upper,
                                                        int unsigned alignment,
                                                        output longint signed sampled_value);
  longint signed first_value;
  longint signed remainder;
  longint unsigned slot_count;
  longint unsigned selected_slot;

  sampled_value = 0;
  if (range_upper <= range_lower || alignment == 0) begin
    return 1'b0;
  end
  remainder = range_lower % longint'(alignment);
  if (remainder == 0) begin
    first_value = range_lower;
  end else if (range_lower > 0) begin
    first_value = range_lower + alignment - remainder;
  end else begin
    first_value = range_lower - remainder;
  end
  if (first_value >= range_upper) begin
    return 1'b0;
  end
  slot_count = (range_upper - 1 - first_value) / alignment + 1;
  selected_slot = $urandom_range(int'(slot_count - 1), 0);
  sampled_value = first_value + longint'(selected_slot * alignment);
  return 1'b1;
endfunction : sample_aligned_value

function bit shmins_sequence_item::sample_creq_base(longint signed base_lower, longint signed base_upper);
  longint signed sampled_base;

  creq_base = '0;
  if (!sample_aligned_value(base_lower, base_upper + 1, data_byte_w(), sampled_base)) begin
    return 1'b0;
  end
  creq_base[MADDR_W-1:0] = sampled_base[MADDR_W-1:0];
  return 1'b1;
endfunction : sample_creq_base

function bit shmins_sequence_item::check_generated_maddrs();
  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N; elem_idx++) begin
      if (!is_active_element(thread_idx, elem_idx)) begin
        continue;
      end
      if (!legal_space_maddr_check(thread_idx, elem_maddr[thread_idx][elem_idx])) begin
        `uvm_error("SHMINS_SPLIT_GENERATED_MADDR",
                   $sformatf("thread=%0d elem=%0d generated maddr=%0d is illegal",
                             thread_idx, elem_idx, elem_maddr[thread_idx][elem_idx]))
        return 1'b0;
      end
    end
  end
  if (!check_active_maddr_byte_uniqueness()) begin
    `uvm_error("SHMINS_SPLIT_GENERATED_COLLISION", "generated active MADDR bytes overlap")
    return 1'b0;
  end
  return 1'b1;
endfunction : check_generated_maddrs

function void shmins_sequence_item::post_randomize();
  generation_retry_count = 0;
  generation_reject_count = 0;
  validation_error_count = 0;
  elem_cnt_max = data_elem_max();
  creq_base = '0;
  foreach (offs_elem[thread_idx, elem_idx]) begin
    offs_elem[thread_idx][elem_idx] = 0;
    elem_maddr[thread_idx][elem_idx] = 0;
  end

  generate_address_fields();
  if (!check_generated_maddrs()) begin
    `uvm_fatal("SHMINS_SPLIT_GENERATED_CHECK_FAILED", "topology generator produced an invalid MADDR model")
  end
  if (!populate_element_addresses()) begin
    `uvm_fatal("SHMINS_SPLIT_ADDRESS_BACKFILL", "failed to backfill logical and physical element addresses")
  end
  if (!generate_m2v_writeback_address()) begin
    `uvm_fatal("SHMINS_SPLIT_M2V_WRITEBACK", "failed to find a byte-disjoint M2V writeback address")
  end
  pack_offsets();
  validate_transaction();
endfunction : post_randomize

function void shmins_sequence_item::pack_offsets();
  int unsigned offset_count;
  int unsigned width;

  offset_count = offs_elem_max();
  width = offs_bit_w();
  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    creq_offs_packed[thread_idx] = '0;
    for (int elem_idx = 0; elem_idx < offset_count && elem_idx < ELEM_MAX_N; elem_idx++) begin
      logic [31:0] raw_bits;

      if (!encode_offset(offs_elem[thread_idx][elem_idx], raw_bits)) begin
        `uvm_fatal("SHMINS_SPLIT_OFFSET_ENCODING",
                   $sformatf("thread=%0d elem=%0d offset=%0d is not encodable",
                             thread_idx, elem_idx, offs_elem[thread_idx][elem_idx]))
      end
      case (width)
        32: creq_offs_packed[thread_idx][elem_idx*32 +: 32] = raw_bits;
        16: creq_offs_packed[thread_idx][elem_idx*16 +: 16] = raw_bits[15:0];
        default: ;
      endcase
    end
  end
endfunction : pack_offsets

function void shmins_sequence_item::validate_transaction();
  bit used_bytes[longint unsigned];

  validation_error_count = 0;
  if ($isunknown(creq_tmsk) || creq_tmsk == '0) begin
    validation_error_count++;
    `uvm_error("SHMINS_SPLIT_INVALID_TMSK", "creq_tmsk must be known and non-zero")
  end
  if (creq_inv_size > 12) begin
    validation_error_count++;
    `uvm_error("SHMINS_SPLIT_INVALID_INV_SIZE",
               $sformatf("creq_inv_size=%0d is outside 0 through 12", creq_inv_size))
  end
  if (!(creq_wpnum inside {1, 2, 4}) || int'(creq_wpid) >= WARP_N) begin
    validation_error_count++;
    `uvm_error("SHMINS_SPLIT_INVALID_WARP",
               $sformatf("creq_wpid=%0d creq_wpnum=%0d", creq_wpid, creq_wpnum))
  end

  for (int thread_idx = 0; thread_idx < THD_N; thread_idx++) begin
    if (data_byte_w() == 0 || int'(creq_len[thread_idx]) % data_byte_w() != 0 ||
        thread_elem_cnt(thread_idx) > data_elem_max()) begin
      validation_error_count++;
      `uvm_error("SHMINS_SPLIT_INVALID_LENGTH",
                 $sformatf("thread=%0d length=%0d dtype=%0d", thread_idx, creq_len[thread_idx], creq_dtype))
      continue;
    end
    for (int elem_idx = 0; elem_idx < thread_elem_cnt(thread_idx) && elem_idx < ELEM_MAX_N; elem_idx++) begin
      longint signed maddr;
      shmins_address_result_t mapped;

      if (!is_active_element(thread_idx, elem_idx)) begin
        continue;
      end
      maddr = calculate_maddr(thread_idx, elem_idx);
      if (maddr != elem_maddr[thread_idx][elem_idx]) begin
        validation_error_count++;
        `uvm_error("SHMINS_SPLIT_MADDR_MODEL_MISMATCH",
                   $sformatf("thread=%0d elem=%0d generated=%0d packed=%0d",
                             thread_idx, elem_idx, elem_maddr[thread_idx][elem_idx], maddr))
      end
      mapped = map_maddr(thread_idx, maddr);
      if (!mapped.valid) begin
        validation_error_count++;
        `uvm_error("SHMINS_SPLIT_INVALID_MADDR",
                   $sformatf("thread=%0d elem=%0d maddr=%0d is illegal", thread_idx, elem_idx, maddr))
        continue;
      end

      if (uniqueness_required()) begin
        for (int byte_lane = 0; byte_lane < data_byte_w(); byte_lane++) begin
          longint unsigned key;

          begin
            shm_physical_addr_t byte_addr = mapped.physical_addr;
            byte_addr.baddr += shm_baddr_t'(byte_lane);
            key = make_physical_byte_key(byte_addr);
          end
          if (used_bytes.exists(key)) begin
            validation_error_count++;
            `uvm_error("SHMINS_SPLIT_BYTE_COLLISION",
                       $sformatf("thread=%0d elem=%0d lane=%0d key=0x%0h", thread_idx, elem_idx, byte_lane, key))
          end else begin
            used_bytes[key] = 1'b1;
          end
        end
      end
    end
  end

  if (validation_error_count != 0) begin
    `uvm_fatal("SHMINS_SPLIT_VALIDATION_FAILED",
               $sformatf("transaction has %0d validation errors", validation_error_count))
  end
endfunction : validate_transaction

function void shmins_sequence_item::generate_address_fields();
  `uvm_fatal("SHMINS_SPLIT_BASE_RANDOMIZE",
             "shmins_sequence_item must be randomized through a topology subclass")
endfunction : generate_address_fields

function longint signed shmins_sequence_item::calculate_maddr(int thread_idx, int elem_idx);
  return -1;
endfunction : calculate_maddr

function void shmins_sequence_item::rtl_to_item();
  {creq_info, creq_space, creq_inv_size, creq_ack_en, creq_itype, creq_atype_g, creq_atype_s, creq_atype_w,
   creq_dtype, creq_rw} = creq_typ;
endfunction : rtl_to_item

function void shmins_sequence_item::item_to_rtl();
  creq_typ = {creq_info, creq_space, creq_inv_size, creq_ack_en, creq_itype, creq_atype_g, creq_atype_s,
              creq_atype_w, creq_dtype, creq_rw};
endfunction : item_to_rtl

function void shmins_sequence_item::do_copy(uvm_object rhs);
  shmins_sequence_item rhs_item;

  super.do_copy(rhs);
  if (!$cast(rhs_item, rhs)) begin
    `uvm_fatal(get_type_name(), "Cast of rhs object failed")
  end

  creq_rw = rhs_item.creq_rw;
  creq_dtype = rhs_item.creq_dtype;
  creq_atype_w = rhs_item.creq_atype_w;
  creq_atype_s = rhs_item.creq_atype_s;
  creq_atype_g = rhs_item.creq_atype_g;
  creq_itype = rhs_item.creq_itype;
  creq_ack_en = rhs_item.creq_ack_en;
  creq_inv_size = rhs_item.creq_inv_size;
  creq_space = rhs_item.creq_space;
  creq_typ = rhs_item.creq_typ;
  creq_info = rhs_item.creq_info;
  creq_id = rhs_item.creq_id;
  creq_wpid = rhs_item.creq_wpid;
  creq_wpnum = rhs_item.creq_wpnum;
  wpid_width = rhs_item.wpid_width;
  creq_vaddr = rhs_item.creq_vaddr;
  creq_base = rhs_item.creq_base;
  creq_tmsk = rhs_item.creq_tmsk;
  delay_cycle = rhs_item.delay_cycle;
  m2v_unique_enable = rhs_item.m2v_unique_enable;
  elem_cnt_max = rhs_item.elem_cnt_max;
  generation_retry_count = rhs_item.generation_retry_count;
  generation_reject_count = rhs_item.generation_reject_count;
  validation_error_count = rhs_item.validation_error_count;

  foreach (creq_prio[index]) creq_prio[index] = rhs_item.creq_prio[index];
  foreach (creq_len[index]) creq_len[index] = rhs_item.creq_len[index];
  foreach (elem_num[index]) elem_num[index] = rhs_item.elem_num[index];
  foreach (creq_vmsk[index]) creq_vmsk[index] = rhs_item.creq_vmsk[index];
  foreach (creq_offs_packed[index]) creq_offs_packed[index] = rhs_item.creq_offs_packed[index];
  foreach (creq_vdat[index]) creq_vdat[index] = rhs_item.creq_vdat[index];
  foreach (offs_elem[thread_idx, elem_idx]) begin
    offs_elem[thread_idx][elem_idx] = rhs_item.offs_elem[thread_idx][elem_idx];
    elem_maddr[thread_idx][elem_idx] = rhs_item.elem_maddr[thread_idx][elem_idx];
    elem_logical_addr[thread_idx][elem_idx] = rhs_item.elem_logical_addr[thread_idx][elem_idx];
    elem_physical_addr[thread_idx][elem_idx] = rhs_item.elem_physical_addr[thread_idx][elem_idx];
  end
endfunction : do_copy

function bit shmins_sequence_item::compare_item(shmins_sequence_item rhs);
  return compare(rhs);
endfunction : compare_item

`endif // INC_SHMINS_SEQUENCE_ITEM_SVH
